apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-deployment
  namespace: webservice
  labels:
    app: recommend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      containers:
        - name: recommend-container
          image: nugulsuhan/recommend-service:0a873d10ce6058bb274bb3908cea14c7f848098f
          ports:
            - containerPort: 10000
