apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-deployment
  namespace: webservice
  labels:
    app: recommend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      containers:
        - name: recommend-container
          image: nugulsuhan/recommend-service:7a5d44e8e104800838641ffb33031c5b9c17b610
          ports:
            - containerPort: 10000
