# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default
# 7개 서비스 리스트
microservices:
  - name: auth-service
    namespace: webservice
    image: nugulsuhan/auth-service
    tag: f3bce01879cb4c39e6f4ac53eb2cbd8829a5385b
    port: 10000
  - name: user-service
    namespace: webservice
    image: nugulsuhan/user-service
    tag: a2ca5683fa4bf2526979ea84d7ef5b53e10de60c
    port: 10000
  - name: stats-service
    namespace: webservice
    image: nugulsuhan/stats-service
    tag: f3bce01879cb4c39e6f4ac53eb2cbd8829a5385b
    port: 10000
  - name: notification-service
    namespace: webservice
    image: nugulsuhan/notification-service
    tag: a2ca5683fa4bf2526979ea84d7ef5b53e10de60c
    port: 10000
  - name: system-service
    namespace: webservice
    image: nugulsuhan/system-service
    tag: a2ca5683fa4bf2526979ea84d7ef5b53e10de60c
    port: 10000
  - name: recommend-service
    namespace: webservice
    image: nugulsuhan/recommend-service
    tag: a2ca5683fa4bf2526979ea84d7ef5b53e10de60c
    port: 10000
  - name: study-service
    namespace: webservice
    image: nugulsuhan/study-service
    tag: a2ca5683fa4bf2526979ea84d7ef5b53e10de60c
    port: 10000
