# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default
# 7개 서비스 리스트
microservices:
  - name: auth-service
    namespace: webservice
    image: nugulsuhan/auth-service
    tag: a5da560f11b550adee0064bcf544405a177a393a
    port: 10000
  - name: user-service
    namespace: webservice
    image: nugulsuhan/user-service
    tag: a06eb089b5132f20a307c4c7709eb307ac70b35d
    port: 10000
  - name: stats-service
    namespace: webservice
    image: nugulsuhan/stats-service
    tag: 9d0dd1b34610d9d55b7eda128b68f31f9043d3e2
    port: 10000
  - name: notification-service
    namespace: webservice
    image: nugulsuhan/notification-service
    tag: 79b753d68c281587609653838320bf2712dbec44
    port: 10000
  - name: system-service
    namespace: webservice
    image: nugulsuhan/system-service
    tag: e51e1d0739d54c3874931175e648ee61413d262e
    port: 10000
  - name: recommend-service
    namespace: webservice
    image: nugulsuhan/recommend-service
    tag: 9217eb869dd6cdba609228d3e306f34a9cf55664
    port: 10000
  - name: study-service
    namespace: webservice
    image: nugulsuhan/study-service
    tag: a76408c2c7e917d78e9d48551ea1e4eef5c8cdc2
    port: 10000
