# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default
# 7개 서비스 리스트
microservices:
  - name: auth-service
    namespace: webservice
    image: nugulsuhan/auth-service
    tag: c10a11b3a4e4550a062ab16f891c99af1a0788e0
    port: 10000
  - name: user-service
    namespace: webservice
    image: nugulsuhan/user-service
    tag: eb1c1b198a387ade4429beddab72949171175ebd
    port: 10000
  - name: stats-service
    namespace: webservice
    image: nugulsuhan/stats-service
    tag: 3f6fbdd9acd4e11ab5648f37b957f90fc1dfdb53
    port: 10000
  - name: notification-service
    namespace: webservice
    image: nugulsuhan/notification-service
    tag: af8efe9e5aacd35640f0274204e4cdcede8c19c5
    port: 10000
  - name: system-service
    namespace: webservice
    image: nugulsuhan/system-service
    tag: 4746903869bf5a3116011e38298b415dc137dcd6
    port: 10000
  - name: recommend-service
    namespace: webservice
    image: nugulsuhan/recommend-service
    tag: a2314a33fd14c65dc8e3f9fe4a66977f949f7e9d
    port: 10000
  - name: study-service
    namespace: webservice
    image: nugulsuhan/study-service
    tag: ac919dd878dff6aaa3ae5f60efee8cb970c17046
    port: 10000
