# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default

# 7개 서비스 리스트
microservices:
  - name: user-service
    namespace: webservice
    image: my-repo/auth
    tag: v1.0
    port: 10000
    
  - name: stats-service
    namespace: webservice
    image: my-repo/payment
    tag: v2.3
    port: 10000

  - name: notification-service
    namespace: webservice
    image: my-repo/noti
    tag: latest
    port: 10000

  - name: system-service
    namespace: webservice
    image: my-repo/noti
    tag: latest
    port: 10000

  - name: recommend-service
    namespace: webservice
    image: my-repo/noti
    tag: latest
    port: 10000

  - name: study-service
    namespace: webservice
    image: my-repo/noti
    tag: latest
    port: 10000
