# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default
# 7개 서비스 리스트
microservices:
  - name: auth-service
    namespace: webservice
    image: nugulsuhan/auth-service
    tag: 284fbebf32e447bcb01949994677e775c2cf02ce
    port: 10000
  - name: user-service
    namespace: webservice
    image: nugulsuhan/user-service
    tag: 7e0da73772df007539d090e55454cd86c369671b
    port: 10000
  - name: stats-service
    namespace: webservice
    image: nugulsuhan/stats-service
    tag: faa10805788379262b7e1b2b120eff1983d87474
    port: 10000
  - name: notification-service
    namespace: webservice
    image: nugulsuhan/notification-service
    tag: 5724dcfc925c1dce7016ad52311f7b9c4e70be91
    port: 10000
  - name: system-service
    namespace: webservice
    image: nugulsuhan/system-service
    tag: 202df138b225d77841c456c417e594e320443cd4
    port: 10000
  - name: recommend-service
    namespace: webservice
    image: nugulsuhan/recommend-service
    tag: 202df138b225d77841c456c417e594e320443cd4
    port: 10000
  - name: study-service
    namespace: webservice
    image: nugulsuhan/study-service
    tag: 284fbebf32e447bcb01949994677e775c2cf02ce
    port: 10000
