# 모든 서비스가 공유할 기본 설정
destinationServer: https://kubernetes.default.svc
project: default
# 7개 서비스 리스트
microservices:
  - name: auth-service
    namespace: webservice
    image: nugulsuhan/auth-service
    tag: edb84331948e3a2bcf71a3d12e4e21055dd43cef
    port: 10000
  - name: user-service
    namespace: webservice
    image: nugulsuhan/user-service
    tag: 90aaafcbe49b22563505b74e1b0a1fb9c2e74f20
    port: 10000
  - name: stats-service
    namespace: webservice
    image: nugulsuhan/stats-service
    tag: ff774429380c481ad7621c14a0edf0706fb29440
    port: 10000
  - name: notification-service
    namespace: webservice
    image: nugulsuhan/notification-service
    tag: ff774429380c481ad7621c14a0edf0706fb29440
    port: 10000
  - name: system-service
    namespace: webservice
    image: nugulsuhan/system-service
    tag: f03ba15f53ae7cfe28ac65264c30d222d1d6cf77
    port: 10000
  - name: recommend-service
    namespace: webservice
    image: nugulsuhan/recommend-service
    tag: ff774429380c481ad7621c14a0edf0706fb29440
    port: 10000
  - name: study-service
    namespace: webservice
    image: nugulsuhan/study-service
    tag: ff774429380c481ad7621c14a0edf0706fb29440
    port: 10000
