apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-deployment
  namespace: webservice
  labels:
    app: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-container
          image: nugulsuhan/stats-service:d3529aa5b66807a0367b12c185840a70b5b52ed8
          ports:
            - containerPort: 10000
