apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-deployment
  namespace: webservice
  labels:
    app: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-container
          image: nugulsuhan/p_frontend:1ec65b2773d82f25c66e71a748147f17cc448260
          ports:
            - containerPort: 10000
