apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  namespace: webservice
  labels:
    app: system-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-service
  template:
    metadata:
      labels:
        app: system-service
    spec:
      containers:
        - name: system-container
          image: nugulsuhan/system-service:1f3c735f85e99b10bca03b3173f861ef24b01f7c
          ports:
            - containerPort: 10000
