apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1           # HPAê°€ ì ìš©ë˜ë©´ ì´ ìˆ«ìëŠ” ë¬´ì‹œë©ë‹ˆë‹¤ (ì²˜ìŒì—ë§Œ ìœ íš¨)
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: nugulsuhan/auth-service:7bb85fb902fa357f97a918a78cd4681d94a5f5c0
        
        # ğŸ‘‡ [ì¤‘ìš”] ì´ ë¶€ë¶„ì´ ì—†ìœ¼ë©´ HPA ì ˆëŒ€ ì•ˆ ë©ë‹ˆë‹¤!
        resources:
          requests:
            cpu: "200m"     # 0.2 ì½”ì–´ (ê¸°ì¤€ì )
            memory: "128Mi"
          limits:
            cpu: "500m"     # 0.5 ì½”ì–´ (ìµœëŒ€ì¹˜)
            memory: "256Mi"
