apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studylinker-studysvc
  namespace: webservice
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: studylinker
    alb.ingress.kubernetes.io/group.order: "5"

    alb.ingress.kubernetes.io/healthcheck-path: "/actuator/health"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"

    # === ALB ì „ì²´ì— ì ìš©ë˜ëŠ” ì˜µì…˜ë“¤ ===
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - host: gachon.studylink.click
      http:
        paths:
          # ğŸ‘‡ [ì¶”ê°€ë¨] Auth ì„œë¹„ìŠ¤ (10000ë²ˆ í¬íŠ¸)
          # êµ¬ì²´ì ì¸ ê²½ë¡œë¥¼ ë¨¼ì € ì ì–´ì£¼ëŠ” ê²ƒì´ ê´€ë¡€ìƒ ì¢‹ìŠµë‹ˆë‹¤.
          - path: /api/group-members
            pathType: Prefix
            backend:
              service:
                name: study-service    
                port:
                  number: 10000  
                       
          - path: /api/study-groups
            pathType: Prefix
            backend:
              service:
                name: study-service    
                port:
                  number: 10000 

          - path: /api/study-posts
            pathType: Prefix
            backend:
              service:
                name: study-service    
                port:
                  number: 10000 

          - path: /api/study-schedules
            pathType: Prefix
            backend:
              service:
                name: study-service    
                port:
                  number: 10000
                  
          - path: /api/attendance
            pathType: Prefix
            backend:
              service:
                name: study-service    
                port:
                  number: 10000

         

       
