apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port | default 10000 }}
      targetPort: {{ .Values.service.port | default 10000 }}
  selector:
    app: {{ .Release.Name }}
