apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-deployment
spec:
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
    spec:
      containers:
      - name: study-container
        image: nugulsuhan/auth-service:e4ade165140a55ff60e4c6b228b7f1274813bff0
        
        # ğŸ‘‡ [ì¤‘ìš”] ì´ ë¶€ë¶„ì´ ì—†ìœ¼ë©´ HPA ì ˆëŒ€ ì•ˆ ë©ë‹ˆë‹¤!
        resources:
          requests:
            cpu: "200m"     # 0.2 ì½”ì–´ (ê¸°ì¤€ì )
            memory: "128Mi"
          limits:
            cpu: "500m"     # 0.5 ì½”ì–´ (ìµœëŒ€ì¹˜)
            memory: "256Mi"
